graph LR
    a[프로그램 시작]
    b[factorial = 1]
    c[i = 5]
    d[i > 0 ?]
    e[factorial *= i]
    f[i를 1 감소] 
    g[팩토리얼 출력]
    z[프로그램 종료]
    a-->b
    b-->c
    c-->d
    d-->|true| e
    e-->f
    f-->d
    d--->|false| g
    g-->z

style a fill:black,color:white
style z fill:black,color:white
style d fill:firebrick,color:white