graph LR
    a[A출발 B경우 C도착 : 3개]
    a --> b[A출발 C경우 B도착 : 2개]
    a --> c[A출발 B경우 C도착 : 1개]
    a --> d[B출발 A경우 C도착 : 2개]
    b --> e[A출발 B경우 C도착 : 1개]
    b --> f[A출발 C경우 B도착 : 1개]
    b --> g[C출발 A경우 B도착 : 1개]
    d --> h[B출발 C경우 A도착 : 1개]
    d --> i[B출발 A경우 C도착 : 1개]
    d --> j[A출발 B경우 C도착 : 1개]

style b fill:dodgerblue,color:white
style d fill:dodgerblue,color:white
style c fill:firebrick,color:white
style e fill:firebrick,color:white
style f fill:firebrick,color:white
style g fill:firebrick,color:white
style h fill:firebrick,color:white
style i fill:firebrick,color:white
style j fill:firebrick,color:white
