classDiagram 
    Button <|-- MenuButton
    Button <|-- CaptureButton
    Button <|-- ExitButton
    class Button {
        push()
    }
    class MenuButton {
        push()
    }
    class CaptureButton {
        push()
    }
    class ExitButton {
        push()
    }