sequenceDiagram
    Note left of main(): 프로그램 실행
    main()->>+plus(): 호출(call) - 10, 20 전달
    plus()->>-main(): 반환(return) - 30
    Note Over main(),plus():호출 시 어떤 값을 전달해도<br>int 데이터 1개가 반환된다
    Note left of main(): 프로그램 종료
