classDiagram 
    class 아이폰13 {
        -전화번호
        -색상
        +전화()
        +문자()
        +사진촬영()
        +아이튠즈()
        +음성인식()
    }
    class 아이폰14 {
        -전화번호
        -색상
        +전화()
        +문자()
        +사진촬영()
        +아이튠즈()
        +특수촬영()
    }
    class 갤럭시폴드4 {
        -전화번호
        -색상
        +전화()
        +문자()
        +사진촬영()
        +삼성페이()
        +화면분할()
    }
    class 갤럭시S23 {
        -전화번호
        -색상
        +전화()
        +문자()
        +사진촬영()
        +삼성페이()
        +펜터치()
    }
