graph TD
    a[번호 - 1\n이름 - 유비\n성별 - 남자\n나이 - 50]
    b[번호 - 2\n이름 - 관우\n성별 - 남자\n나이 - 42]
    c[번호 - 3\n이름 - 마초\n성별 - 남자\n나이 - 35]
    d[번호 - 4\n이름 - 대교\n성별 - 여자\n나이 - 40]
    e[번호 - 5\n이름 - 소교\n성별 - 여자\n나이 - 37]
    f[번호 - 6\n이름 - 초선\n성별 - 여자\n나이 - 30]

style a text-align:left
style b text-align:left
style c text-align:left
style d text-align:left
style e text-align:left
style f text-align:left