sequenceDiagram
    Note left of main(): 프로그램 실행
    main()->>+factorial(5): 호출
    factorial(5)->>+factorial(4): 호출
    factorial(4)->>+factorial(3): 호출
    factorial(3)->>+factorial(2): 호출
    factorial(2)->>+factorial(1): 호출
    factorial(1)-->>-factorial(2): return 1
    Note right of factorial(2): 1 반환
    factorial(2)-->>-factorial(3): return 2 * factorial(1)
    Note right of factorial(3): 2 반환
    factorial(3)-->>-factorial(4): return 3 * factorial(2)
    Note right of factorial(4): 6 반환
    factorial(4)-->>-factorial(5): return 4 * factorial(3)
    Note right of factorial(5): 24 반환
    factorial(5)-->>-main(): return 5 * factoral(4)
    Note right of main(): 120 반환
    Note left of main(): 프로그램 종료
