classDiagram 
    휴대폰 <|-- 아이폰
    휴대폰 <|-- 갤럭시
    아이폰 <|-- 아이폰13
    아이폰 <|-- 아이폰14
    갤럭시 <|-- 갤럭시폴드4
    갤럭시 <|-- 갤럭시S23
    class 휴대폰 {
        -전화번호
        -색상
        +전화()
        +문자()
        +사진촬영()
    }
    class 아이폰 {
        +아이튠즈()
    }
    class 아이폰13 {
        +음성인식()
    }
    class 아이폰14 {
        +특수촬영()
    }
    class 갤럭시 {
        +삼성페이()
    }
    class 갤럭시폴드4 {
        +화면분할()
    }
    class 갤럭시S23 {
        +펜터치()
    }
