graph TD
    a[30, 50, 20, 10, 40]
    b[30, 50, 20]
    c[10, 40]
    d[30, 50]
    e[30]
    f[50]
    g[20]
    h[10]
    i[40]
    j[30,50]
    k[20,30,50]
    l[10,40]
    m[10,20,30,40,50]
    a-->|divide|b
    a-->|divide|c
    b-->|divide|d
    b-->|divide|g
    d-->|divide|e
    d-->|divide|f
    c-->|divide|h
    c-->|divide|i
    e-->|combine|j
    f-->|combine|j
    j-->|combine|k
    g-->|combine|k
    h-->|combine|l
    i-->|combine|l
    k-->|combine|m
    l-->|combine|m

style b fill:firebrick,color:white
style c fill:firebrick,color:white
style d fill:firebrick,color:white
style e fill:firebrick,color:white
style f fill:firebrick,color:white
style g fill:dodgerblue,color:white
style h fill:firebrick,color:white
style i fill:firebrick,color:white
style j fill:dodgerblue,color:white
style k fill:dodgerblue,color:white
style l fill:dodgerblue,color:white
