classDiagram 
    Vehicle <|-- Car
    Vehicle <|-- Kickboard
    Car <|-- Sonata
    Car <|-- Ray

    class Car {
        drive():void
    }
    class Sonata {
        drive():void
        music():void
    }